### ISSUE TITLE
Bug with 2 monitors

### ISSUE THREAD

**Issue by kitt3911** [zhanghai/gnome-shell-extension-transparent-top-bar#12]
When working with more than one monitor, I observe the following:
on the main monitor everything works well, but on the additional one the transparency does not work

i am using extension [Extension](https://extensions.gnome.org/extension/921/multi-monitors-add-on/)

**Comment by zhanghai** [comment]
GNOME Shell shows only one panel out of the box, so the extension you used make it a non-standard behavior. Of course someone may add support for the linked extension, but I don't have the time and intention to add and maintain it, because I don't use it. If you want it you can fork this repo and work on that, which some people are already doing.

This extension is mostly a resurrection of what was in the original GNOME shell implementation for transparent top bar, and I want to keep it simple so my current plan is to only do absolutely necessary changes & maintenance.
